addons:
  postgresql: "12"
  apt:
    update: true
    packages:
      - postgresql-12
      - postgresql-client-12

env:
  global:
  - PGPORT=5432
  - PGPASSWORD=travis
  - PGUSER=travis

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

before_script:
  - psql --version
  - psql -p "${PGPORT}" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U travis
  - psql -p "${PGPORT}" -c 'CREATE DATABASE finance_test_db;' -U travis
  - psql -p "${PGPORT}" -c "CREATE USER henninb WITH PASSWORD 'monday1';" -U travis
  - psql -p "${PGPORT}" -c 'ALTER USER henninb CREATEDB;' -U travis
  - psql -p "${PGPORT}" -c 'ALTER USER henninb SUPERUSER;' -U travis
  - psql -p "${PGPORT}" -c 'GRANT ALL PRIVILEGES ON DATABASE finance_test_db TO henninb' -U travis

after_script:
  - psql --version

services:
  - postgresql

language: java
jdk:
  - openjdk11
#script: ./gradlew clean test integrationTest functionalTest
script: ./gradlew clean functionalTest

notifications:
  email: henninb@msn.com
git:
  autocrlf: input
