version: "3.7"
services:
  raspi-finance-endpoint:
    image: raspi-finance-endpoint
    build:
      context: ./
      args:
       - APP=raspi-finance-endpoint
       - TIMEZONE=America/Chicago
       - USERNAME=${USER}
       - CURRENT_UID=${CURRENT_UID}
       - CURRENT_GID=${CURRENT_GID}
      dockerfile: Dockerfile
    container_name: raspi-finance-endpoint
    ports:
      - "8443:8443"
    expose:
      - "8443"
    hostname: hornsup-endpoint
    volumes:
      - ./logs:/opt/raspi-finance-endpoint/logs
      - ./excel_in:/opt/raspi-finance-endpoint/excel_in
      - ./json_in:/opt/raspi-finance-endpoint/json_in
    extra_hosts:
      - "hornsup:${HOST_IP}"
      - "raspi:192.168.10.25"
    env_file:
      - env.secrets
    depends_on:
      logstash-server:
         condition: service_healthy
  elasticsearch-server:
    image: elasticsearch:7.14.1
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: elasticsearch-server
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      # - "9300:9300"
    expose:
      - "9200"
    extra_hosts:
      - "hornsup:${HOST_IP}"
    depends_on:
      - logstash-server
  kibana-server:
    image: kibana:7.14.1
    container_name: kibana-server
    ports:
      - "5601:5601"
    expose:
      - "5601"
    depends_on:
      - elasticsearch-server
    extra_hosts:
      - "hornsup:${HOST_IP}"
      - "elasticsearch:${HOST_IP}"
  logstash-server:
    image: logstash:7.14.1
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: logstash-server
    environment:
      - monitoring.elasticsearch.hosts=http://hornsup:9200
    ports:
      - "9600:9600"
      - "4560:4560"
    expose:
      - "9600"
      - "4560"
    volumes:
      - ./logstash-pipeline:/usr/share/logstash/pipeline
    healthcheck:
      test: ["CMD-SHELL", "/bin/true"]
#      test: ["CMD-SHELL", "curl", "-f", "192.168.100.97:9600"]
      interval: 10s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "hornsup:${HOST_IP}"
      - "elasticsearch:${HOST_IP}"
  grafana-server:
    image: grafana/grafana:8.3.3
    user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: grafana-server
    ports:
      - "3001:3000"
    expose:
      - "3001"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    env_file:
      - env.grafana
networks:
  default:
    name: finance-net
volumes:
  elasticsearch-volume:
    driver: local
