version: "3.7"
services:
  varnish-server:
    image: varnish
    hostname: varnish-server
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: varnish-server
    ports:
      - "8080:80"
#      - "6081:6081"
    expose:
      - "8080"
#      - "6081"
    extra_hosts:
      - "hornsup:${HOST_IP}"
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
      - ./default.vcl:/default.vcl
      #- ./varnish-data:/etc/varnish
# volumes:
#   varnish-volume:
#     driver: local
  caddy-server:
    image: caddy
    hostname: caddy-server
    container_name: caddy-server
