services:
  nginx-reverse-proxy-finance:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    hostname: nginx-reverse-proxy-finance
    container_name: nginx-reverse-proxy-finance
    restart: always
    ports:
      - "9443:443"
    expose:
      - "hornsup:${HOST_IP}"
