version: "3.7"
services:
  varnish-server:
    image: varnish
    hostname: varnish-server
    container_name: varnish-server
    restart: always
    ports:
      - "8080:80"
    expose:
      - "8080"
    extra_hosts:
      - "hornsup:${HOST_IP}"
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
    depends_on:
      - nginx-proxy-finance-server

  nginx-proxy-finance-server:
    image: nginx
    hostname: nginx-proxy-finance-server
    container_name: nginx-proxy-finance-server
    restart: always
    ports:
      - "9443:443"
    expose:
      - "9443"
    extra_hosts:
      - "hornsup:${HOST_IP}"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/certs/
# networks:
#   localnetwork:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.10.0/24
#           gateway: 192.168.10.1
