version: "3.7"
services:
  postgresql-server:
    image: postgres:13.4
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: postgresql-server
    ports:
      - "5433:5432"
    expose:
      - "5433"
    env_file:
      - env.postgresql
    hostname: postgresql-server
    volumes:
      # - ./postgresql-data:/var/lib/postgresql/data
      postgresql-volume:/var/lib/postgresql/data
  raspi-finance-endpoint:
    depends_on:
      - postgresql-server
volumes:
  postgresql-volume:
    driver: local
