server:
  tomcat:
    connection-timeout: 10s
  port: 8080
  ssl:
    key-store: classpath:hornsup-raspi-finance-keystore.p12
    key-store-password: dummy
    key-store-type: pkcs12
    key-alias: hornsup
    key-password: dummy
    enabled: false
    enabled-protocols: TLSv1.2
spring:
  security:
    user:
      name: dummy
      password: dummy
  application:
    name: raspi-finance-endpoint

  # ===============================
  # = Jackson Settings
  # ===============================
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null
    mapper.accept-case-insensitive-enums: true
    time-zone: America/Chicago
  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:h2:mem:finance_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    hikari:
#      schema: public
  sql:
    init:
      continue-on-error: false
      mode: never
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  # Show or not log for each sql query
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: h2
  #    properties:
  #      hibernate:
  #        jdbc:
  #          time_zone: UTC

  # ===============================
  # = Flyway
  # ===============================
  flyway:
    enabled: false
    user: dummy
    password: dummy
    url: jdbc:h2:mem:finance_db
    baseline-on-migrate: true
    baseline-version: 0
    #    schemas: prod
    locations: classpath:db/migration/prod
    validate-on-migrate: true

# ===============================
# = Logging
# ===============================
logging:
  config: classpath:logback-prod.groovy




debug: false

